<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Vugen" productVer="2021" os="" host="DESKTOP-G16F30O"><DocLocation><![CDATA[C:\Users\Solirius\Documents\VuGen\Scripts\LoadRunner2021\001_CreateCase_UIPerformanceTestv3]]></DocLocation></General>
<Doc rID="T1"   productName= "Vugen"  >
<DName><![CDATA[001_CreateCase_UIPerformanceTestv3]]></DName>
<Res><![CDATA[result1]]></Res>
<Action rID="T2">
<AName><![CDATA[Init]]></AName>
<Summary sTime="31/03/2021 - 08:36:46" eTime="31/03/2021 - 08:36:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="5" >
<Disp><![CDATA[Init Summary]]></Disp>
</NodeArgs>
</Action>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action]]></AName>
<Summary sTime="31/03/2021 - 08:36:49" eTime="31/03/2021 - 08:36:49" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="8" >
<Disp><![CDATA[Action Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T5">
<AName><![CDATA[LaunchHomePage]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Navigate to https://manage-case.perf...tform.hmcts.net/ was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:36:53]]></Time>
<TimeTick>1617176213</TimeTick>
<NodeArgs eType="General" icon="0" nRep="11" status="Passed" >
<Disp><![CDATA[Navigate]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="31/03/2021 - 08:36:49" eTime="31/03/2021 - 08:36:53" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="10" status="Passed" >
<Disp><![CDATA[LaunchHomePage Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T7">
<AName><![CDATA[SignIn]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Verify Sign in's Visible Text contains Sign in was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:36:57]]></Time>
<TimeTick>1617176217</TimeTick>
<NodeArgs eType="General" icon="0" nRep="14" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.1: Click on Email address textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:00]]></Time>
<TimeTick>1617176220</TimeTick>
<NodeArgs eType="General" icon="0" nRep="15" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.2: Type ccdloadtest4501@gmail.com in Email address textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:11]]></Time>
<TimeTick>1617176231</TimeTick>
<NodeArgs eType="General" icon="0" nRep="16" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.3: Click on Password passwordbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:13]]></Time>
<TimeTick>1617176233</TimeTick>
<NodeArgs eType="General" icon="0" nRep="17" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Type ********** in Password passwordbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:17]]></Time>
<TimeTick>1617176237</TimeTick>
<NodeArgs eType="General" icon="0" nRep="18" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.5: Click on Sign in button was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:21]]></Time>
<TimeTick>1617176241</TimeTick>
<NodeArgs eType="General" icon="0" nRep="19" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Verify Case List's Visible Text contains Case List was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:23]]></Time>
<TimeTick>1617176243</TimeTick>
<NodeArgs eType="General" icon="0" nRep="20" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="31/03/2021 - 08:36:53" eTime="31/03/2021 - 08:37:23" passed="7" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="13" status="Passed" >
<Disp><![CDATA[SignIn Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T15">
<AName><![CDATA[SelectCreateCase]]></AName>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Verify Case List's Visible Text contains Case List was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:23]]></Time>
<TimeTick>1617176243</TimeTick>
<NodeArgs eType="General" icon="0" nRep="23" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Click on Create case link was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:27]]></Time>
<TimeTick>1617176247</TimeTick>
<NodeArgs eType="General" icon="0" nRep="24" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="31/03/2021 - 08:37:23" eTime="31/03/2021 - 08:37:27" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="22" status="Passed" >
<Disp><![CDATA[SelectCreateCase Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T18">
<AName><![CDATA[CreateCase]]></AName>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Select Leeds - Singles from Case type listbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:29]]></Time>
<TimeTick>1617176249</TimeTick>
<NodeArgs eType="General" icon="0" nRep="27" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Select Create Case from Event listbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:32]]></Time>
<TimeTick>1617176252</TimeTick>
<NodeArgs eType="General" icon="0" nRep="28" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on Start button was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:47]]></Time>
<TimeTick>1617176267</TimeTick>
<NodeArgs eType="General" icon="0" nRep="29" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="31/03/2021 - 08:37:27" eTime="31/03/2021 - 08:37:47" passed="3" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="26" status="Passed" >
<Disp><![CDATA[CreateCase Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T22">
<AName><![CDATA[CreateCaseSubmission]]></AName>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Verify Date of Receipt's Visible Text contains Date of Receipt was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:47]]></Time>
<TimeTick>1617176267</TimeTick>
<NodeArgs eType="General" icon="0" nRep="32" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.1: Click on Day textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:50]]></Time>
<TimeTick>1617176270</TimeTick>
<NodeArgs eType="General" icon="0" nRep="33" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.2: Type 25 in Day textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:51]]></Time>
<TimeTick>1617176271</TimeTick>
<NodeArgs eType="General" icon="0" nRep="34" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.3: Type 03 in Month textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:52]]></Time>
<TimeTick>1617176272</TimeTick>
<NodeArgs eType="General" icon="0" nRep="35" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Type 2021 in Year textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:54]]></Time>
<TimeTick>1617176274</TimeTick>
<NodeArgs eType="General" icon="0" nRep="36" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.5: Click on Submission ReferenceSubmission... textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:37:57]]></Time>
<TimeTick>1617176277</TimeTick>
<NodeArgs eType="General" icon="0" nRep="37" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.6: Type 001001001001 in Submission ReferenceSubmission... textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:02]]></Time>
<TimeTick>1617176282</TimeTick>
<NodeArgs eType="General" icon="0" nRep="38" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on Continue button was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:06]]></Time>
<TimeTick>1617176286</TimeTick>
<NodeArgs eType="General" icon="0" nRep="39" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="31/03/2021 - 08:37:47" eTime="31/03/2021 - 08:38:06" passed="8" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="31" status="Passed" >
<Disp><![CDATA[CreateCaseSubmission Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T31">
<AName><![CDATA[CreareCasePersonDetails]]></AName>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Verify Type of claimant's Visible Text contains Type of claimant was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:06]]></Time>
<TimeTick>1617176286</TimeTick>
<NodeArgs eType="General" icon="0" nRep="42" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[2.1: Select Mr from Title (Optional) listbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:06]]></Time>
<TimeTick>1617176286</TimeTick>
<NodeArgs eType="General" icon="0" nRep="43" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.2: Click on First Name textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:07]]></Time>
<TimeTick>1617176287</TimeTick>
<NodeArgs eType="General" icon="0" nRep="44" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.3: Type UI in First Name textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:09]]></Time>
<TimeTick>1617176289</TimeTick>
<NodeArgs eType="General" icon="0" nRep="45" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Type PerfTest001 in Last Name textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:12]]></Time>
<TimeTick>1617176292</TimeTick>
<NodeArgs eType="General" icon="0" nRep="46" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.5: Click on Day textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:13]]></Time>
<TimeTick>1617176293</TimeTick>
<NodeArgs eType="General" icon="0" nRep="47" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.6: Type 01 in Day textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:15]]></Time>
<TimeTick>1617176295</TimeTick>
<NodeArgs eType="General" icon="0" nRep="48" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.7: Type 01 in Month textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:16]]></Time>
<TimeTick>1617176296</TimeTick>
<NodeArgs eType="General" icon="0" nRep="49" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.8: Type 2000 in Year textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:18]]></Time>
<TimeTick>1617176298</TimeTick>
<NodeArgs eType="General" icon="0" nRep="50" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[2.9: Select Male from Gender (Optional) listbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:19]]></Time>
<TimeTick>1617176299</TimeTick>
<NodeArgs eType="General" icon="0" nRep="51" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.10: Click on Enter a UK postcode textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:19]]></Time>
<TimeTick>1617176299</TimeTick>
<NodeArgs eType="General" icon="0" nRep="52" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.11: Type sw1h9hg in Enter a UK postcode textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:23]]></Time>
<TimeTick>1617176303</TimeTick>
<NodeArgs eType="General" icon="0" nRep="53" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.12: Click on Find address button was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:26]]></Time>
<TimeTick>1617176306</TimeTick>
<NodeArgs eType="General" icon="0" nRep="54" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[2.13: Select Flat 75, Vandon Court, 6...y France, London from Select an address listbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:26]]></Time>
<TimeTick>1617176306</TimeTick>
<NodeArgs eType="General" icon="0" nRep="55" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Click on Continue button was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:30]]></Time>
<TimeTick>1617176310</TimeTick>
<NodeArgs eType="General" icon="0" nRep="56" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="31/03/2021 - 08:38:06" eTime="31/03/2021 - 08:38:30" passed="15" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="41" status="Passed" >
<Disp><![CDATA[CreareCasePersonDetails Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T47">
<AName><![CDATA[CreateCaseAddtionalDetails]]></AName>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Verify Respondents's Visible Text contains Respondents was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:30]]></Time>
<TimeTick>1617176310</TimeTick>
<NodeArgs eType="General" icon="0" nRep="59" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.1: Click on Add new button was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:33]]></Time>
<TimeTick>1617176313</TimeTick>
<NodeArgs eType="General" icon="0" nRep="60" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.2: Type Mr UI PerformanceTester001 in Name of respondent textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:44]]></Time>
<TimeTick>1617176324</TimeTick>
<NodeArgs eType="General" icon="0" nRep="61" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.3: Click on Yes  was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:46]]></Time>
<TimeTick>1617176326</TimeTick>
<NodeArgs eType="General" icon="0" nRep="62" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.4: Click on ACAS Certificate Number textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:47]]></Time>
<TimeTick>1617176327</TimeTick>
<NodeArgs eType="General" icon="0" nRep="63" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.5: Type 001001001001 in ACAS Certificate Number textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:52]]></Time>
<TimeTick>1617176332</TimeTick>
<NodeArgs eType="General" icon="0" nRep="64" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.6: Click on Enter a UK postcode textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:53]]></Time>
<TimeTick>1617176333</TimeTick>
<NodeArgs eType="General" icon="0" nRep="65" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Type]]></Obj>
<Details plainTxt="False" ><![CDATA[2.7: Type sw1h 9hg in Enter a UK postcode textbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:56]]></Time>
<TimeTick>1617176336</TimeTick>
<NodeArgs eType="General" icon="0" nRep="66" status="Passed" >
<Disp><![CDATA[Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.8: Click on Find address button was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:38:58]]></Time>
<TimeTick>1617176338</TimeTick>
<NodeArgs eType="General" icon="0" nRep="67" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[2.9: Select Flat 75, Vandon Court, 6...y France, London from Select an address listbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:39:01]]></Time>
<TimeTick>1617176341</TimeTick>
<NodeArgs eType="General" icon="0" nRep="68" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2.10: Click on Continue button was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:39:03]]></Time>
<TimeTick>1617176343</TimeTick>
<NodeArgs eType="General" icon="0" nRep="69" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="31/03/2021 - 08:38:30" eTime="31/03/2021 - 08:39:03" passed="11" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="58" status="Passed" >
<Disp><![CDATA[CreateCaseAddtionalDetails Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T59">
<AName><![CDATA[CreateCaseSubmit]]></AName>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Verify Is this the same as the...'s Visible Text contains Is this the same as the ...'s work address? was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:39:04]]></Time>
<TimeTick>1617176344</TimeTick>
<NodeArgs eType="General" icon="0" nRep="72" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Click on Yes  was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:39:06]]></Time>
<TimeTick>1617176346</TimeTick>
<NodeArgs eType="General" icon="0" nRep="73" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Select]]></Obj>
<Details plainTxt="False" ><![CDATA[3: Select Mr UI PerformanceTester0..., United Kingdom from Please select the Respondent... listbox was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:39:08]]></Time>
<TimeTick>1617176348</TimeTick>
<NodeArgs eType="General" icon="0" nRep="74" status="Passed" >
<Disp><![CDATA[Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[4.1: Click on Continue button was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:39:11]]></Time>
<TimeTick>1617176351</TimeTick>
<NodeArgs eType="General" icon="0" nRep="75" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[4.2: Click on Continue button was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:39:14]]></Time>
<TimeTick>1617176354</TimeTick>
<NodeArgs eType="General" icon="0" nRep="76" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[4.3: Click on No  was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:39:15]]></Time>
<TimeTick>1617176355</TimeTick>
<NodeArgs eType="General" icon="0" nRep="77" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[4.4: Click on Continue button was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:39:21]]></Time>
<TimeTick>1617176361</TimeTick>
<NodeArgs eType="General" icon="0" nRep="78" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[5: Click on Submit button was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:39:30]]></Time>
<TimeTick>1617176370</TimeTick>
<NodeArgs eType="General" icon="0" nRep="79" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="31/03/2021 - 08:39:03" eTime="31/03/2021 - 08:39:30" passed="8" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="71" status="Passed" >
<Disp><![CDATA[CreateCaseSubmit Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T68">
<AName><![CDATA[SubmitCase]]></AName>
<Summary sTime="31/03/2021 - 08:39:30" eTime="31/03/2021 - 08:39:30" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="81" >
<Disp><![CDATA[SubmitCase Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T69">
<AName><![CDATA[SignOut]]></AName>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Click]]></Obj>
<Details plainTxt="False" ><![CDATA[1: Click on Sign out link was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:39:33]]></Time>
<TimeTick>1617176373</TimeTick>
<NodeArgs eType="General" icon="0" nRep="84" status="Passed" >
<Disp><![CDATA[Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Verify]]></Obj>
<Details plainTxt="False" ><![CDATA[2: Verify Sign in's Visible Text contains Sign in was finished]]></Details>
<Time><![CDATA[31/03/2021 - 08:39:33]]></Time>
<TimeTick>1617176373</TimeTick>
<NodeArgs eType="General" icon="0" nRep="85" status="Passed" >
<Disp><![CDATA[Verify]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="31/03/2021 - 08:39:30" eTime="31/03/2021 - 08:39:33" passed="2" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="2" nRep="83" status="Passed" >
<Disp><![CDATA[SignOut Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Passed" >
<Disp><![CDATA[001_CreateCase_UIPerformanceTestv3 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T72" iterID="2" >
<Action rID="T73">
<AName><![CDATA[Action]]></AName>